<Workspace Version="1.3.2.2480" X="-792.144211790407" Y="-1253.48887494789" zoom="1.24165004332912" ScaleFactor="1" Name="8c" Description="" ID="b874f5f7-cb7c-4d7f-9976-7cc39a808512" Category="VRIM.Geometry.world XZ.08">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Circle" resolvedName="Autodesk.DesignScript.Geometry.Circle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Arc" resolvedName="Autodesk.DesignScript.Geometry.Arc" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="EllipseArc" resolvedName="Autodesk.DesignScript.Geometry.EllipseArc" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="71972ae0-1cd1-43f2-9712-c0ac6a96494c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="459.844639165007" y="404" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="HW:double[]={10,10};" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3fd036c2-1c9b-43fb-a6ea-26ec045d4266" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="349" y="537.760611345568" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="StartPt: var=Point.ByCoordinates(0,0,0);" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="d5633b54-03c1-4905-9bdf-de112feb5195" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1456.00337079895" y="900.51809570659" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="InfoGeom=OUT[0];&#xA;End=OUT[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2700c620-49bf-4a26-b6b8-2007cfa177db" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1732.7311918723" y="887.83081231146" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="8c" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="cedbbbe8-830a-4bf6-920f-e5fa5ac9c8df" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1738.65159737983" y="948.5516097123" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="EndPt" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="9b6b62d6-4143-4445-8db1-5e062710c4fb" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="8c" x="786.505524118361" y="426.317584420459" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="// Copyright(c) 2017, Elisabetta Caterina Giovannini&#xA;// Alma Mater Studiorum - University of Bologna&#xA;// VRIM project&#xA;// www.unibo.it/sitoweb/elisabettacaterina.giovannini/en&#xA;// elisabettacaterina.giovannini@unibo.it&#xA;&#xA;//Measurements - 8c&#xA;H1=HW[0];&#xA;W1=HW[1];&#xA;W0= StartPt.X;&#xA;H0= StartPt.Z;&#xA;&#xA;//Coordinate System(-x,z)&#xA;Ax = W0-W1;&#xA;Az = H0;&#xA;Ex = W0-(W1/2);&#xA;Bx = W0;&#xA;Hz = H0+(H1/2);&#xA;Dz = H0+H1;&#xA;&#xA;//9 Points grid&#xA;yPt= StartPt.Y;&#xA;A = Point.ByCoordinates(Ax,yPt,Az);&#xA;E = Point.ByCoordinates(Ex,yPt,Az);&#xA;B = Point.ByCoordinates(Bx,yPt,Az);&#xA;H = Point.ByCoordinates(Ax,yPt,Hz);&#xA;O = Point.ByCoordinates(Ex,yPt,Hz);&#xA;F = Point.ByCoordinates(Bx,yPt,Hz);&#xA;D = Point.ByCoordinates(Ax,yPt,Dz);&#xA;G = Point.ByCoordinates(Ex,yPt,Dz);&#xA;C = Point.ByCoordinates(Bx,yPt,Dz);&#xA;&#xA;//Geometry 8c&#xA;geometry8c = [Imperative]&#xA;{&#xA;if(H1&gt;W1)&#xA;{&#xA;//Geometry by ellipse&#xA;r1 = W1/2;&#xA;r2 = H1/2;&#xA;planeE = Plane.ByThreePoints(E, B, O);&#xA;planeG = Plane.ByThreePoints(G, D, O);&#xA;Arc1 = EllipseArc.ByPlaneRadiiAngles(planeE, r2, r1, 0, 90);&#xA;Arc2 = EllipseArc.ByPlaneRadiiAngles(planeG, r2, r1, 0, 90);&#xA;geometry8c = {Arc1, Arc2};&#xA;JoinCurves = PolyCurve.ByJoinedCurves(geometry8c);&#xA;return= {JoinCurves, D};&#xA;}&#xA;else&#xA;{&#xA;//Geometry by arc&#xA;x1 = B.DistanceTo(D);&#xA;r=((x1/14)*6);&#xA;planeB = Plane.ByThreePoints(B, F, E);&#xA;planeO = Plane.ByThreePoints(O, G, H);&#xA;planeD = Plane.ByThreePoints(D, H, G);&#xA;circleB = Circle.ByPlaneRadius(planeB, r);&#xA;circleO = Circle.ByPlaneRadius(planeO, r);&#xA;circleD = Circle.ByPlaneRadius(planeD, r);&#xA;ipB = circleO.Intersect(circleB);&#xA;ipD = circleO.Intersect(circleD);&#xA;p1 = ipB[1];&#xA;p2 = ipB[0];&#xA;p3 = ipD[1];&#xA;p4 = ipD[0];&#xA;Arc1 = Arc.ByCenterPointStartPointEndPoint(p2, O, B);&#xA;Arc2 = Arc.ByCenterPointStartPointEndPoint(p3, O, D);&#xA;geometry8c = {Arc1, Arc2};&#xA;JoinCurves = PolyCurve.ByJoinedCurves(geometry8c);&#xA;return= {JoinCurves, D};&#xA;}&#xA;};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="71972ae0-1cd1-43f2-9712-c0ac6a96494c" start_index="0" end="9b6b62d6-4143-4445-8db1-5e062710c4fb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3fd036c2-1c9b-43fb-a6ea-26ec045d4266" start_index="0" end="9b6b62d6-4143-4445-8db1-5e062710c4fb" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5633b54-03c1-4905-9bdf-de112feb5195" start_index="0" end="2700c620-49bf-4a26-b6b8-2007cfa177db" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5633b54-03c1-4905-9bdf-de112feb5195" start_index="1" end="cedbbbe8-830a-4bf6-920f-e5fa5ac9c8df" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9b6b62d6-4143-4445-8db1-5e062710c4fb" start_index="20" end="d5633b54-03c1-4905-9bdf-de112feb5195" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="7.59534842823782" eyeY="27.9989316468311" eyeZ="32.4125969279563" lookX="-12.5953484282378" lookY="-16.9989316468311" lookZ="-40.4125969279563" upX="-0.0491102481959841" upY="0.986285601537235" upZ="-0.157571874782495" />
  </Cameras>
</Workspace>